# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdfbaafee5d17f36930a9e53fd76ea9d315c92f0e9a38f5a7207eace305032bbf99e98a9e2f6df4776df745110f1d43c9d4ea8e756ff5760537066f2db6e4db1

test:
  secret_key_base: 59558ebba28db317994597ba3fdc8c4e2ac991432fd0f9bcb8f9dcafcac0a97cdb2001f68f8fceedaa5328b119bd11704407e46780fd74164a78e6a9c4ff4924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
